### ISSUE TITLE
Inclusion of faces for some modes

### ISSUE THREAD

**Issue by drigomen** [bbatsov/zenburn-emacs#127]
Hi everyone.

I'm very glad with the current status of this theme and its features, but I'd like to suggest some modes that you could cover with default pretty faces matching this awesome theme.
- auto-highlight-mode: it could use a lighter background that do not interfere on the foreground.
- highlight-parentheses: its default matching face conflicts with the zenburn face for non-matching braces in show-paren mode. Both modes can be used together, so that could be misleading.
- icycles: there is a lot of cobalt blue everywhere...
- fic-ext-mode or hl-todo

**Comment by bbatsov** [comment]
I don't plan to work on this, but PRs would be welcome.
