### ISSUE TITLE
updates for flycheck-mode

### ISSUE THREAD

**Issue by biffhero** [bbatsov/zenburn-emacs#184]
I tried flycheck-color-mode-line, from melpa , but nothing changed with my errors.

I tried the solarized theme, and it changed my modeline background as well as my big-fringe, as I thought it should.  I added the following lines in zenburn:

   `(compilation-mode-line-exit
     ((,class (:inherit compilation-info :foreground ,zenburn-green :weight bold))))
   `(compilation-mode-line-fail
     ((,class (:inherit compilation-error :foreground ,zenburn-red :weight bold))))
   `(compilation-mode-line-run ((,class (:foreground ,zenburn-orange :weight bold))))

But that didn't work, either.  I used 
M-x customize-group RET flycheck-faces RET
and modified two items as now saved to my emacs-customizations.el file.

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(flycheck-fringe-error ((t (:inherit error :background "red" :foreground "#BC8383" :weight bold))))
 '(flycheck-fringe-warning ((t (:inherit warning :background "gold3" :foreground "#F0DFAF" :weight bold)))))

I obviously don't know how to edit the theme by itself, so please accept this as a pull request in the form of a bug report.

Thanks,
Rob

**Comment by bbatsov** [comment]
//cc @lunaryorn

**Comment by lunaryorn** [comment]
@bbatsov  I'm not exactly sure what the issue is, nor what I'm supposed to comment on this issue.  

@biffhero Would you mind to fix the formatting of your comment, and explain exactly—best by a screenshot—how the theme looked and which colours you changed?

**Comment by LC43** [comment]
what i think OP meant was that zenburn and flycheck-color-mode-line don't work out of the box.

i had to do just what he did, otherwise the fringe didn't reflect the status clearly.
