### ISSUE TITLE
function calls' colour

### ISSUE THREAD

**Issue by sinadogru** [bbatsov/zenburn-emacs#196]
I am not sure if this right place to post it but if not i apologize.

Well it is not an issue, actually it is a request;

Is there a way to customizing function calls' colour instead of a default colour to more notably one so it would be easier to read codes of languages like procedural programming.

Thanks,
Sina

**Comment by bbatsov** [comment]
This depends on the major modes, but I've never seen an Emacs major mode which uses font-locking for function calls. Most use them only for function definitions. This is totally outside the scope of themes.

**Comment by sinadogru** [comment]
Thank you bba.
