### ISSUE TITLE
ugly fringe indicator in Emacs 25

### ISSUE THREAD

**Issue by bixuanzju** [bbatsov/zenburn-emacs#197]
After trying Emacs 25, I find the face of fringe indicators rather ugly and obtrusive

![screen shot 2015-06-06 at 11 05 22 am](https://cloud.githubusercontent.com/assets/1680704/8018044/f52cdd72-0c3b-11e5-80fa-10c355534b2a.png)

or like this

![screen shot 2015-06-06 at 11 07 24 am](https://cloud.githubusercontent.com/assets/1680704/8018055/4d9263f6-0c3c-11e5-8708-95e146ed21a7.png)

I've no idea what have changed in Emacs 25

**Comment by c256** [comment]
FWIW, the upper screenshot gives you an empty-lines indicator that I don't see by default (in emacs 25, started with -Q, then with zenburn loaded), so maybe it's a setting on your end?

The lower screenshot shows the same wrapped-line indicator that I see by default.

**Comment by bixuanzju** [comment]
>FWIW, the upper screenshot gives you an empty-lines indicator that I don't see by default (in emacs 25, started with -Q, then with zenburn loaded), so maybe it's a setting on your end?

yes, by `(setq indicate-empty-lines t)`. The problem is, before Emacs 25, it is less that obtrusive compared to the background.

**Comment by bbatsov** [comment]
Yeah, noticed this myself recently, but I'm not sure what's the best fix for this.
