### ISSUE TITLE
Release v2.3

### ISSUE THREAD

**Issue by joonoro** [bbatsov/zenburn-emacs#207]
Zenburn support for Magit 2.1.0 was introduced in 2b6d6e5c8b101a34f3345b2316adaab281e04813 and since then Magit 2.1.0 is now in melpa-stable, but the Zenburn version in melpa-stable is still v2.2 and doesn't include the support for Magit 2.1.0 that was added.

In other words: someone using melpa-stable will be stuck on Magit 2.1.0 with a Zenburn that doesn't support it.

Maybe it's time for a new release?

**Comment by bbatsov** [comment]
Just released 2.3.
