### ISSUE TITLE
helm-header changes clash with custom-theme-set-faces header-line

### ISSUE THREAD

**Issue by issue-dispenser** [bbatsov/zenburn-emacs#210]
This is a copy of emacs-helm/helm#1139

Somehow the global header-line seeps into the helm-header as shown below at the top right:

![helm-header](https://cloud.githubusercontent.com/assets/13922417/9458624/97e1a70a-4aad-11e5-8034-04c542229386.png)

**Comment by michael-heerdegen** [comment]
What exactly is the bug?  The short darker gray end of the header line above the fringe and scroll bar, ~ 2 chars long?  If that is what you mean, Thierry probably misunderstood what you meant, that is a bug in helm unrelated to this theme, please come back there if you meant that.  Thanks.

**Comment by issue-dispenser** [comment]
Yes, it's the dark bit just above the scroll bar. Thanks for confirming that.
