### ISSUE TITLE
Remove certain face customizations

### ISSUE THREAD

**Issue by holocronweaver** [bbatsov/zenburn-emacs#237]
Is there a way to remove particular custom faces from a theme by adding lines to a user init file? Or is directly editing the theme source the only means?

Background: Recently org-habit-*-face customizations were added that resulted in org-habit bars being very hard to differentiate for someone who is red-green colorblind. I want to remove these custom faces since the default colors were easy to read and looked fine.

**Comment by fice-t** [comment]
You can use `custom-theme-set-faces` for this. For example:

```elisp
(custom-theme-set-faces
 'zenburn
 '(org-habit-ready-face)
 '(org-habit-alert-face))
```

**Comment by holocronweaver** [comment]
For posterity, this did indeed solve my problem. Thanks!

**Comment by impaktor** [comment]
Possibly something to put in the README.md?
