### ISSUE TITLE
customize pdf-tools midnight mode colors

### ISSUE THREAD

**Issue by ericdanan** [bbatsov/zenburn-emacs#238]
The `pdf-tools` package has a "midnight mode" with bright text on dark background (`pdf-view-midnight-minor-mode`). I find that the default colors don't fit well with the `zenburn` theme and the following looks much nicer:

```
(zenburn-with-color-variables
  (custom-theme-set-variables
   'zenburn
   `(pdf-view-midnight-colors '(,zenburn-fg . ,zenburn-bg-05))))
```

The `-05` is so that the page background can be distinguished from both the `emacs` window background (`zenburn-bg`) and selected text (`zenburn-bg-1`). Here are screenshots (sorry for the poor quality, the relevant window is on the right hand side and I selected a paragraph of text). With the default colors:

![default](https://cloud.githubusercontent.com/assets/11611353/14723680/93faa0c4-0812-11e6-9647-a3271f904fb5.PNG)

And with the customization:

![custom](https://cloud.githubusercontent.com/assets/11611353/14723715/bea93998-0812-11e6-9b34-7eee690dad20.PNG)

This seems natural to me, so perhaps you want to include it in the theme (if so I can send you a PR if you want, and if not I can of course simply keep the customization in my `init.el`).

**Comment by bbatsov** [comment]
PR welcome!

**Comment by ericdanan** [comment]
I just sent it (plus another one to fix a typo). Let me know if anyting else is needed.
