### ISSUE TITLE
line-num-mode not work after enable zenburn-theme

### ISSUE THREAD

**Issue by suiwenfeng** [bbatsov/zenburn-emacs#239]
![line-num-model-not-work](https://cloud.githubusercontent.com/assets/2735407/14767539/f98d4e66-09f5-11e6-9048-b3ac75fe9450.png)

you can see that 'line-num-model' is enabled but the line number not show up.

**Comment by bbatsov** [comment]
`M-x linum-mode` works just fine for me.

**Comment by suiwenfeng** [comment]
Thanks

**Comment by suiwenfeng** [comment]
Linum mode is a **buffer-local** minor mode.

it works only in **buffer** scope!!!

**Comment by suiwenfeng** [comment]
please use global-linum-mode
