### ISSUE TITLE
'box' attribute

### ISSUE THREAD

**Issue by joinvim** [bbatsov/zenburn-emacs#246]
How set 'box' attribute on Helm sections to 'nil'?
![default](https://cloud.githubusercontent.com/assets/19364650/15423998/e4408634-1e88-11e6-82f1-a9f2699c294d.jpg)

**Comment by yamad** [comment]
Try something like:

```{elisp}
(custom-set-faces '(helm-source-header ((t (:box nil)))))
```

**Comment by joinvim** [comment]
Thanks, maybe it's works, but i now turn off helm.
