### ISSUE TITLE
Background in git-commit-mode is too bright

### ISSUE THREAD

**Issue by arichiardi** [bbatsov/zenburn-emacs#267]
Hello folks! I am really liking this theme. Just a lil' thing I would like to fix and a picture is worth a thousand words:

![2017-02-17-164253_661x332_scrot](https://cloud.githubusercontent.com/assets/1724788/23088330/61e551a4-f530-11e6-97dc-e8eb99f92692.png)

A bit less bright would make it less washed out imho, opinions?

**Comment by bbatsov** [comment]
All colours look extremely strange here. Are you using terminal Emacs?

**Comment by arichiardi** [comment]
Yes this is in the terminal.

**Comment by bbatsov** [comment]
Guess you didn't set `export TERM=xterm-256color`. If you open some GUI Emacs you'll see how the colours are supposed to actually look.

**Comment by arichiardi** [comment]
Ah so I am using `urxvt`, 256 color as well so TERM is different. That might be the problem then.

**Comment by arichiardi** [comment]
You gave me a very good hint, I found my answer [here](http://unix.stackexchange.com/a/196567/88220). I have to install `rxvt-unicode-256color`.
