### ISSUE TITLE
`cperl-mode` faces not covered by zenburn

### ISSUE THREAD

**Issue by kennyballou** [bbatsov/zenburn-emacs#285]
Recently looking at some perl code, and tried to use `cperl-mode` [because it's better(?)][1]. However, it seems to expose some faces that are not supported or covered by the zenburn theme.

For example, these are the few I noticed right away:

- `cperl-nonoverrideable-face`

- `cperl-array-face`

- `cperl-hash-face`

With some more time, I may be able to submit a PR to fix this, but for now I will be using `perl-mode` as the `cperl-mode` colours are simply too jarring.

[1]: https://www.emacswiki.org/emacs/CPerlMode

**Comment by bbatsov** [comment]
@kennyballou Customizing those is really simple, so you should really look into submitting a PR. It's basically a line per face.

**Comment by impaktor** [comment]
@kennyballou M-x `describe-face` is your friend.

**Comment by kennyballou** [comment]
On 2018年01月11日 20:21 GMT, Bozhidar Batsov wrote:
> @kennyballou Customizing those is really simple, so you should 
> really look into submitting a PR. It's basically a line per 
> face.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the 
> thread.

Yeah, I figured this was pretty easy.  I just haven't had time to 
focus
on it yet.  I should be able to do something the next couple of 
days though!
