### ISSUE TITLE
Theme writes to custom-file

### ISSUE THREAD

**Issue by sirikid** [bbatsov/zenburn-emacs#289]
It seems the theme writes its settings from [this block][1] to `custom-file`. Is this expected behavior?

[1]: https://github.com/bbatsov/zenburn-emacs/blob/a26323ca3029d653f658b8236ae9528d242c885b/zenburn-theme.el#L1370-L1406

**Comment by basil-conto** [comment]
This sounds like an aspect of the [Customize](https://www.gnu.org/software/emacs/manual/html_node/emacs/Easy-Customization.html) interface, possibly brought about by something in your configuration. I, for example, do not use that interface for persistent settings and my `custom-file` never gets written without my instigating it.

Given your configuration or how you use the Customize interface, you'll probably get similar results irrespective of the particular theme. For example, try replacing `zenburn` with `tango`.

**Comment by sirikid** [comment]
Sorry, it seems I have not quite understand Custom yet.
