### ISSUE TITLE
not working with use-package

### ISSUE THREAD

**Issue by jtkDvlp** [bbatsov/zenburn-emacs#319]
It seems the theme does not work with use-package. I guess it is caused by the name of the package "zenburn" and its files "zenburn-theme".

**Comment by basil-conto** [comment]
Although I no longer use `use-package` or `zenburn`, I used them together for many moons and I cannot imagine how a change in either could make them incompatible with each other.

When reporting issues, merely saying "it doesn't work" doesn't provide anyone with enough information to understand and debug the issue, let alone fix it. Please explain in as much detail as possible what your configuration looks like, how you load and enable these packages, how you start Emacs, what you see at each step, and how reality does not match your expectations.

> I guess it is caused by the name of the package "zenburn" and its files "zenburn-theme".

Naming issues in the context of loading packages usually boil down to pilot errors when trying to use [named features](https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html) in conjunction with [deferred loading](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html). For example,

```el
(use-package zenburn ...)
```

has a different effect to

```el
(use-package zenburn-theme ...)
```

which in turn is different to

```el
(use-package "zenburn" ...)
```

or

```el
(use-package "zenburn-theme" ...)
```

IIRC I once tried to explain some of these difference in an Emacs SE post: https://emacs.stackexchange.com/a/36803/15748. In this case I think `(use-package zenburn-theme ...)` is the most appropriate one, seeing as both the ELPA package and the feature provided are called `zenburn-theme`. Which one are you trying to use?

Note also that `use-package` does not automatically call `load-theme`; you have to do this yourself.

**Comment by jtkDvlp** [comment]
Thank you for your reply. No pilot error, careless mistake. Mislead by the theme name itself I used zenburn instead of zenburn-theme.

So working version of course:
(use-package
  zenburn-theme ;; only zenburn is wrong
  :config
  (load-theme 'zenburn))
