### ISSUE TITLE
org-document-title is always scaled

### ISSUE THREAD

**Issue by matteo-l** [bbatsov/zenburn-emacs#321]
The scaling of face `org-document-title` is not controlled by any user option. I think  it should be enabled only when `zenburn-scale-org-headlines`, or a new dedicated user option, is true.

**Comment by bbatsov** [comment]
Yeah, I agree. Patches welcome!

**Comment by matteo-l** [comment]
Do you think it's better to define a new option `zenburn-scale-org-title` or use `zenburn-scale-org-headlines`?
