### ISSUE TITLE
How would one go about adding slightly more contrast?

### ISSUE THREAD

**Issue by VizorKit** [bbatsov/zenburn-emacs#350]
For example, just a bit brighter white. slightly darker gray background, etc.

Is there a higher contrast option?

I am on Windows opening emacs from git bash shell, and just looking at the .emacs file and I don't see any of the bolding shown in the readme's initial screenshot. Is there something I need to do to get that to work?

![image](https://user-images.githubusercontent.com/57162749/94093223-55138400-fde2-11ea-9014-28b152e28d8e.png)

**Comment by VizorKit** [comment]
I was able to get nearly how I desired with just a few random buffers with this setup.
```
  (setq zenburn-override-colors-alist
	'(("zenburn-red" . "#de7a78")
	  ("zenburn-bg-05" . "#292928")
	  ("zenburn-bg" . "#3b3837")))
```

I'm sure I will make some more tweaks in the future :)

**Comment by ksjogo** [comment]
My fork is generating the colors dynamically based on some constants, you could potenially tweak these to your usecase: https://github.com/ksjogo/labburn-theme/blob/master/labburn-theme.el
