### ISSUE TITLE
Mute all colours a bit

### ISSUE THREAD

**Issue by ghost** [bbatsov/zenburn-emacs#353]
I think this is hands down the best theme for Emacs. I don't like too much and too bright colours. I've been using this theme for a while now, but recently I started feeling that some colours are a bit too bright. Is it possible to mute down all colours without overriding each colour?

**Comment by AndrewBurdyug** [comment]
Especially plain diffs and magit diff look very bright for me, i had to change them to more "flat"..

**Comment by ledohod** [comment]
Having looked at the colour palette in the source code, I think there are only few colours I need to override, especially mute down green+4 and make the background a bit darker. So, manual overriding will work for me.

**Comment by impaktor** [comment]
Github recently introduced a "discussion" feature, (example: https://github.com/vercel/next.js/discussions ), that can be activated in the github repo settings. I'm thinking if that was to be turned on, then the bug tracker wouldn't have to be used for issues that are questions / discussions.

**Comment by bbatsov** [comment]
I'll enable it soon. For someone to notice I also have to update the contribution templates, as everyone goes to tickets by default. :-)

There's no built-in way to mute/brighten all colours, but I guess it'd be trivial to just modify the list with the color definitions.

**Comment by ksjogo** [comment]
My customzied version https://github.com/ksjogo/labburn-theme/ has more muted colours and gives you a lightness const which you could tune to your liking as all colours are calculated in lab colour space.

**Comment by impaktor** [comment]
@ksjogo the png linked in your labburn page gives "Cannot proxy the given URL", would be interesting to see some examples of what it looks like.

**Comment by ledohod** [comment]
> My customzied version https://github.com/ksjogo/labburn-theme/ has more muted colours and gives you a lightness const which you could tune to your liking as all colours are calculated in lab colour space.
> It also has all/most bold attributes removed as these look too bright imo.

Thanks, the colours indeed look more muted. Also, you are right about the bold faces, I think it's better to have them as normal.

**Comment by bbatsov** [comment]
@ksjogo Btw, it seems to me it would have been easier for you to just have defined your new colours and used `(setq zenburn-override-colors-alist ...` with them. Then you wouldn't need to fork and track the upstream theme. I've pondered at some point adding some functionality to defined derived themes (e.g. like what exists in Solarized), but in the end I opted to keep Zenburn as simple as possible.
