### ISSUE TITLE
Line numbers' size stays fixed with `text-scale-adjust` in `display-line-numbers-mode`

### ISSUE THREAD

**Issue by mageecoe** [bbatsov/zenburn-emacs#359]
I use `display-line-numbers-mode` instead of `linum-mode`, and often use `text-scale-adjust` to increase and/or decrease size of buffer text. With this theme, the line numbers' size stays fixed, leading to results like those displayed in the below images. 

An annoying effect of not scaling the line numbers is that more lines do not fit vertically on the screen when "zooming out", which is a typical motivation for (temporarily) scaling the font size.

Similar themes, like `doom-zenburn` do not suffer from this issue, but I like the choices of colors of this theme slightly better, and would prefer to use it if this issue could be fixed.

<img width="163" alt="Screenshot 2022-02-20 at 21 49 20" src="https://user-images.githubusercontent.com/4500376/154863876-b961a9de-50f3-44fd-9d13-12d7b1ce3c95.png">

<img width="239" alt="Screenshot 2022-02-20 at 21 49 52" src="https://user-images.githubusercontent.com/4500376/154863891-0dabe926-830a-4af3-be3c-0ce0d6094bdd.png">

**Comment by bbatsov** [comment]
Thanks for the report. I guess we should just check what's different in both themes with respect to this. Generally I'm a bit puzzled as to what'd be causing the difference in behavior.

**Comment by mageecoe** [comment]
Thanks for the quick reply. I had never peeked at lisp code for color themes before, and it wasn’t immediate to me how to fix the issue since codes look somewhat different in different themes. I was able to get the line numbers to grow/shrink by mimicking one-liners related to line numbering from the vivendi themes by Prot. But that seemed to change a few colors in the zenburn theme.

So instead of spending time on finding out how to fix it correctly, I figured a color-theme author that knows the code can fix it a lot faster… hopefully.

**Comment by mageecoe** [comment]
I took a quick look again, and noted that this line seems to be the culprit: 
https://github.com/bbatsov/zenburn-emacs/blob/50e9bb9bcd62edf29d29a29b2b9b6b845db68174/zenburn-theme.el#L270

By commenting that line, scaling works again in `display-line-numbers-mode`.  But then the colors are lost. Perhaps you understand why scaling breaks when that line is added?
