### ISSUE TITLE
can't autoload zenburn on emacs 24

### ISSUE THREAD

**Issue by Txellenne** [bbatsov/zenburn-emacs#89]
Hi there. 
I can't autoload zenburn-theme in emacs (24.1.1) on Fedora 17
I installed the file by using (I got marmalade repo installed):
        `M-x package-install RET zenburn-theme RET`

The package got download at ~/.emacs.d/elpa/ (a file called "zenburn-theme-1.5" whose content is: zenburn-theme.el, zenburn-theme-autoloads.el, zenburn-theme-pkg.el, zenburn-theme-pkg.elc) 

I can actually load it at sessions by:
       `M-x load-theme RET zenburn RET` 

The issue is to load it automatically. To have that I wrote in my .emacs file:
        (add-to-list 'load-path "~/.emacs.d/elpa/zenburn-theme-1.5/")
        (load-theme 'zenburn-theme t)  (I also tried (load-theme 'zenburn t) but unsuccessful)

I already tried adding just: "(load-theme 'zenburn t)" as instructed at https://github.com/bbatsov/zenburn-emacs 
But whenever I do so emacs says it can't find theme, when starting). 

Could you pls post your package-load-path and the coding you include on your .emacs, pls??
I would appreciate it. 

PS. I also made it manually. Dropping the package at ~/.emacs.d/theme and adding to my .emacs file:
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'zenburn t)

but unsuccessful.
Once again I'd appreciate your help on this issue.
Txe

**Comment by fdhenard** [comment]
> WORKAROUND
> ...
> (add-hook 'after-init-hook 'zenburn-init)

Awesome.  Thanks!

> ...Incidentally, I think that I should be able to do this without the defun. How?

Use an anonymous [function](http://www.gnu.org/software/emacs/manual/html_node/elisp/Anonymous-Functions.html)
Here's mine:

```elisp
(add-hook 'after-init-hook (lambda () (load-theme 'zenburn t)))
```
